name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
      - name: Lint
        run: pnpm lint

  test:
    name: Test
    needs: [lint]
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
      - name: Test
        run: pnpm test:coverage
